/* common types */
<digit>      ::= [0-9]
<number>     ::= (<digit> | ".")+
<letter>     ::= [a-z] | [A-Z]
<identifier> ::= <letter> (<letter> | <digit>)*

<literal>    ::= <number> | "true" | "false"

/* the root program node */
<program>   ::= (<statement> ";")+
<statement> ::= <var_def> | <expression>

<var_def> ::= "let " <identifier> "=" <expression>

/* expression tree. further down = higher precedence */
<expression>          ::= <additive_expression>
<additive_expression> ::= <term> (("+" | "-") <term>)*
<term>                ::= <factor> (("*" | "/") <factor>)*
<unary_prefix>        ::= "-" <unary_prefix> | <unary_postfix>
<unary_postfix>       ::= <fn_call> "!"*
<fn_call>             ::= <factor> ("(" <fn_call_arg_list> ")")*
<factor>              ::= <literal> | "(" <expression> ")" | <identifier>

/* complex grammar constructs */
<fn_call_arg_list>    ::= (<expression> ("," <expression>)*)?